# This is a basic workflow to help you get started with Actions

name: Deploy Cluster

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - cluster/*.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cluster_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        file: [default.yml]
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          is_target_changed: ${{ matrix.file }}
    - if: steps.changes.outputs.is_target_changed == 'false'
      run: echo "${{ matrix.file }} is not changed."
    - if: steps.changes.outputs.is_target_changed == 'true'
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_REMOTE_IP }}
        username: ${{ secrets.AWS_REMOTE_USER }}
        key: ${{ secrets.AWS_REMOTE_SSH_KEY }}
        port: ${{ secrets.AWS_REMOTE_SSH_PORT }}
        script: |
          cd ~
          git clone "https://${{ secrets.LOGIN_ID }}:${{ secrets.LOGIN_ACCESS_TOKEN }}@github.com/4by4inc-pixell/AWS-Ray-Cluster-Control.git"
          cd ./AWS-Ray-Cluster-Control ;; git pull
          mkdir ${{ matrix.file }}
